% This script assumes your matlab instance has the workspace generated by
% running mayo_verify.m

outdir = "golden_ascii_data";
mkdir( outdir );
%%
fout = fopen(sprintf("%s/EPK.ascii", outdir ), "w" );
for epk_val = epk_golden.'
    if epk_val > 15
        fprintf( fout, "%X\n", epk_val );
    else
        fprintf( fout, "0%X\n", epk_val );
    end

end
fclose( fout );
%%
fout = fopen(sprintf("%s/p_golden.ascii", outdir), "w" );
for slice_idx = 1:size(P,3)
    for row_idx = 1:size(P,2)
        for col_idx = 1:size(P,1)
            val = P(row_idx, col_idx, slice_idx);
            fprintf( fout, "%X\n", val.x );

        end
    end
end
fclose( fout );

%%
fout = fopen(sprintf("%s/sig.ascii", outdir ), "w" );
for sig_val = sig_golden(1:n*k/2).'
    if sig_val > 15
        fprintf( fout, "%X\n", sig_val );
    else
        fprintf( fout, "0%X\n", sig_val );
    end

end
fclose( fout );
%%
fout = fopen(sprintf("%s/s_golden.ascii", outdir ), "w" );
for s_val = s_golden.'
        fprintf( fout, "%X\n", s_val );
end
fclose( fout );
%% y_long_golden
fout = fopen(sprintf("%s/y_long_golden.ascii", outdir ), "w" );
for s_val = y_long_golden.'
        fprintf( fout, "%X\n", s_val );
end
fclose( fout );
%% y_golden
fout = fopen(sprintf("%s/y_golden.ascii", outdir ), "w" );
for s_val = y_golden.'
        fprintf( fout, "%X\n", s_val );
end
fclose( fout );
%% Galois Test Vectors
in_0 = gf( randi(15, 64, 1 ), 4);
in_1 = gf( randi(15, 64, 1 ), 4);
out_add = in_0 + in_1;
out_mul = in_0 .* in_1;

fout = fopen(sprintf("%s/galois_operations.ascii", outdir ), "w" );
for ii = 1:length( in_0 )
    v_in_0 = in_0(ii); 
    v_in_1 = in_1(ii); 
    v_out_add = out_add(ii); 
    v_out_mul = out_mul(ii); 
    fprintf( fout, "%X %X %X %X\n", v_in_0.x, v_in_1.x, v_out_add.x, v_out_mul.x );
end
fclose( fout );
